from transformers import LlamaTokenizerFast
from nltk.tokenize import word_tokenize

tokenizer = LlamaTokenizerFast.from_pretrained("hf-internal-testing/llama-tokenizer")
print(len(tokenizer.encode("The proportion of patients’ hospitalization for COVID 19 treatment was also lower among ginger users (28.0%) than in nonusers (38.0%).46 In a study from Bangladesh, a few cases of cured COVID-19 patients were described who consumed home medicines containing ginger in mixes of various herbs with or without the use of additional treatments.47 According to the results from a Tunisian study, treatment of a few cases of COVID-19 with home medicines containing ginger in combinations with other herbs reduced disease symptoms.48 In some parts of Africa, acclaimed remedies containing ginger in mixes of various herbs were also used for the management of COVID-19.49 The results from a clinical trial study from Iran indicate that a combination therapy by ginger and Echinacea in suspected COVID-19 outpatients attenuated some of their clinical symptoms (breath shortness, coughing and muscular pain) in comparison with those treated with a standard protocol using hydroxychloroquine, alone.50 In addition, the hospitalization rate in the intervention group (2.0%) was lower than that in the control group (6.0%).50 The results from a randomized-controlled study showed that the patients with ARDS who were fed an enteral diet enriched with ginger extract for 21 days exhibited greater oxygenation, lower serum concentrations of IL-1, IL-6, and TNF-α, and spent shorter time on mechanical ventilation compared to control group. However, organ failure, barotrauma and mortality rate similarly occurred in ginger-treated patients and control group.20 Ginger can have beneficial impacts in patients suffering from pulmonary complications such as ARDS, lung fibrosis, and pneumonia, as well as sepsis, all of which are signs observed in COVID-19.51 Overall, the aforesaid evidence indicates that more high-quality controlled trials need to confirm the effectiveness and safety of ginger or its compound in COVID-19 patients. A clinical trial is going on in Iran, in which a total of 84 patients with COVID-19 were randomly classified into two groups of each with 42 participants, including intervention and control groups. The intervention group will be administrated standard treatment protocol plus 1000 mg ginger three times daily for seven days, whereas the control group will be received standard treatment plus placebo tablets at the same dose and timing.52 \
Anti-inflammatory, immunomodulatory, and anti-oxidative potentials of gingerGinger potentials to modulate the neutrophil responsesThe neutrophils from COVID-19 display an activation status. Neutrophil activation and degranulation can promote inflammation and hemorrhagic lesions in the pulmonary system of COVID-19 patients.53 Lymphopenia and a higher neutrophil-lymphocyte ratio also happen in patients with severe COVID-19.54 Patients with COVID-19 exhibited high circulating levels of calprotectin (a neutrophil activation marker) and its quantities were higher in patients who had progressed to the severe form of the disease.55 During viral respiratory infections, the quantities of C-X-C motif chemokine ligand (CXCL) 8, which is a neutrophil-recruitment chemokine, in the secretions of airways were positively related to the count of neutrophils, amount of neutrophil-derived elastase, and clinical scores.56 \
, \
57 Activated neutrophils displayed NETosis, autophagy, and reactive oxygen species (ROS) generation leading to lung injury, which promotes ARDS.56 The interaction of viral proteins with TLR4 triggers NETosis which consists of large ")))


print(len(tokenizer.encode("Provide an answer to the question using the provided evidence and contrasting it with your internal knowledge\nEvidence:\nQuestion:\nYour answer:")))
print(len(word_tokenize("Provide an answer to the question using the provided evidence and contrasting it with your internal knowledge\nEvidence:\nQuestion:\nYour answer:")))